apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-1
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: crawler-1
        spec:
          containers:
          - name: crawler-1
            image: batteryho/crawler:0.1
            # args: ["--mode", "1" ]
          restartPolicy: OnFailure