apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-1
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: crawler-1
        spec:
          containers:
          - name: crawler-1
            image: batteryho/crawler:v0.6
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 8200
          restartPolicy: Never